name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate Docker Build
        run: |
          echo "Simulating Docker build..."
          sleep 2
      
      - name: Simulate Trivy Scan
        run: |
          echo "Scanning image..."
          sleep 2
      
      - name: Simulate Docker Push
        run: |
          echo "Pushing image..."
          sleep 2
      
      - name: Simulate Deploy
        run: |
          echo "Deploying to cluster..."
          sleep 2

      # ✅ SUCCESS EMAIL (Simple Text)
      - name: Send Success Email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: true
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "✅ Pipeline Success - ${{ github.repository }}"
          to: kunjbhuva301@gmail.com
          from: kunjbhuva.me@gmail.com
          body: "Successfully completed!"

      # ❌ FAILURE EMAIL (Simple Text)
      - name: Send Failure Email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: true
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "❌ Pipeline Failed - ${{ github.repository }}"
          to: kunjbhuva301@gmail.com
          from: kunjbhuva.me@gmail.com
          body: "Pipeline failed. Please check the logs."
