name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate Docker Build
        run: |
          echo "Simulating Docker build..."
          sleep 2
      - name: Simulate Trivy Scan
        run: |
          echo "Scanning image..."
          sleep 2
      - name: Simulate Docker Push
        run: |
          echo "Pushing image..."
          sleep 2
      - name: Simulate Deploy
        run: |
          echo "Deploying to cluster..."
          sleep 2

      # ✅ SUCCESS EMAIL (Styled)
      - name: Send Success Email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "✅ Pipeline Success - ${{ github.repository }}"
          to: kunjbhuva301@gmail.com
          from: kunjbhuva.me@gmail.com
          content_type: text/html
          body: >
            <!DOCTYPE html>
            <html>
            <head>
              <style>
                body {
                  background: linear-gradient(135deg, #43e97b, #38f9d7);
                  font-family: Arial, sans-serif;
                  color: #fff;
                  text-align: center;
                  padding: 40px;
                }
                .box {
                  background: rgba(255,255,255,0.1);
                  padding: 30px;
                  border-radius: 12px;
                  box-shadow: 0 4px 20px rgba(0,0,0,0.2);
                  display: inline-block;
                  animation: fadeIn 2s ease;
                }
                @keyframes fadeIn {
                  from { opacity: 0; transform: scale(0.9); }
                  to { opacity: 1; transform: scale(1); }
                }
                h1 {
                  font-size: 28px;
                  margin-bottom: 10px;
                }
                p {
                  font-size: 16px;
                }
                a {
                  background: white;
                  color: #0072ff;
                  padding: 10px 20px;
                  border-radius: 8px;
                  text-decoration: none;
                  font-weight: bold;
                  display: inline-block;
                  margin-top: 15px;
                }
                a:hover {
                  background: #0072ff;
                  color: white;
                }
              </style>
            </head>
            <body>
              <div class="box">
                <h1>🎉 Pipeline Succeeded!</h1>
                <p><b>Repository:</b> ${{ github.repository }}</p>
                <p><b>Run Number:</b> ${{ github.run_number }}</p>
                <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Build Logs</a>
              </div>
            </body>
            </html>

      # ❌ FAILURE EMAIL (Styled)
      - name: Send Failure Email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "❌ Pipeline Failed - ${{ github.repository }}"
          to: kunjbhuva301@gmail.com
          from: kunjbhuva.me@gmail.com
          content_type: text/html
          body: >
            <!DOCTYPE html>
            <html>
            <head>
              <style>
                body {
                  background: linear-gradient(135deg, #ff416c, #ff4b2b);
                  font-family: Arial, sans-serif;
                  color: #fff;
                  text-align: center;
                  padding: 40px;
                }
                .box {
                  background: rgba(255,255,255,0.1);
                  padding: 30px;
                  border-radius: 12px;
                  box-shadow: 0 4px 20px rgba(0,0,0,0.2);
                  display: inline-block;
                  animation: shake 0.8s ease;
                }
                @keyframes shake {
                  0%,100%{transform:translateX(0);}
                  25%{transform:translateX(-6px);}
                  75%{transform:translateX(6px);}
                }
                h1 {
                  font-size: 28px;
                  margin-bottom: 10px;
                }
                a {
                  background: white;
                  color: #ff416c;
                  padding: 10px 20px;
                  border-radius: 8px;
                  text-decoration: none;
                  font-weight: bold;
                  display: inline-block;
                  margin-top: 15px;
                }
                a:hover {
                  background: #ff416c;
                  color: white;
                }
              </style>
            </head>
            <body>
              <div class="box">
                <h1>⚠️ Pipeline Failed!</h1>
                <p>Some steps did not complete successfully.</p>
                <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Logs</a>
              </div>
            </body>
            </html>

